### ISSUE TITLE
Polish app UI

### ISSUE THREAD

**Issue by A-Schmid** [PDA-UR/Screenshotmatcher-2.0#23]

**Comment by AlexW00** [comment]
Added haptic feedback to app buttons,
Status icon (top right in Camera Activity) now resizes back to normal when disconnecting
![CleanShot 2021-09-02 at 15 09 22](https://user-images.githubusercontent.com/55558407/131849299-5be2013b-d99c-4f70-b242-3ba493642aa5.png)
